# Site settings
title: Yeongbin Hwang
description: Yeongbin Hwang / 황영빈
url: https://yeongbin-hwang.github.io/myPortfolio/
# baseurl: "/particle" # the subpath of your site, e.g. /blog

timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

sass:
  sass_dir: _sass

# User settings
username: Yeongbin Hwang
user_title: Security Researcher
user_description: >
  I am a M.S. student <a href="https://www.syssec.kr/" target="_blank">
  @KAIST SysSec Lab</a>. My research interest is to find, analyze, and exploit software and hardware vulnerabilities in cellular network.
  Especially, I'm putting my effort into offensive 5G core network security.    
email: hyb3565800@gmail.com
# twitter: lorem_ipsum
github: yeongbin-hwang
facebook: 
# gplus_username:  lorem_ipsum
