# Site settings
title: Yonghwa Lee
description: Yonghwa Lee / 이용화
url: https://yhlee0078.github.io
# baseurl: "/particle" # the subpath of your site, e.g. /blog

timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

sass:
  sass_dir: _sass

# User settings
username: Yonghwa Lee
user_title: Security Researcher
user_description: >
  I am a M.S. student <a href="https://www.syssec.kr/" target="_blank">
  @KAIST SysSec Lab</a>. My research interest is to find, analyze, and exploit software and hardware vulnerabilities.
  Especially, I'm putting my effort into offensive IoT, Embedded, and CPS(Cyber-Physical System) security.    
  And Since 2018, I've been participating in major CTFs as a member of <a href="https://www.facebook.com/cistcykor" target="_blank"> @CyKor</a>.
email: yhlee0078@kaist.ac.kr
# twitter: lorem_ipsum
github: yhlee0078
facebook: yonghwa.lee.188
# gplus_username:  lorem_ipsum
